// LOAD USER
export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE';

// LOG IN
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

// LOGOUT
export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';

// REGISTER USER
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

//SYSTEM DEMANDS
export const LOAD_SD_LIST_REQUEST = 'LOAD_SD_LIST_REQUEST';
export const LOAD_SD_LIST_SUCCESS = 'LOAD_SD_LIST_SUCCESS';
export const LOAD_SD_LIST_FAILURE = 'LOAD_SD_LIST_FAILURE'; 
	
//SINGLE SYSTEM DEMAND
export const LOAD_SD_REQUEST = 'LOAD_SD_REQUEST';
export const LOAD_SD_SUCCESS = 'LOAD_SD_SUCCESS';
export const LOAD_SD_FAILURE = 'LOAD_SD_FAILURE'; 
